### ISSUE TITLE
Composer failed : Filesystem could not delete , in Docker

### ISSUE THREAD

**Issue by vwasteels** [googleapis/google-api-php-client#2336]
#### Environment details

  - OS: ubuntu:22.04 (Docker) using Laravel 9 with Sail
  - PHP version: 8.1
  - Package name and version: latest 2.12

#### Steps to reproduce

  1. `composer install`
  2. get the following error :

```
sail@769b4c6a1916:/var/www/html$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 1 install, 0 updates, 0 removals
  - Downloading google/apiclient-services (v0.274.0)
  - Installing google/apiclient-services (v0.274.0): Extracting archive
    Install of google/apiclient-services failed

In Filesystem.php line 314:

  Could not delete /var/www/html/vendor/composer/f9cf999e/googleapis-google-api-php-client-services-670c385/src/Contentwarehouse:
```

I tried to :
```chmod -R 777 vendor```

But still ... any idea ?

**Comment by BobDankert** [comment]
Still haven't figured it out. Just to note, I'm running PHP 7.4.10 and having the same issue, running in a docker environment.

**Comment by douglasjam** [comment]
Same for me

PHP
```/var/www/html # php -v
PHP 8.1.11 (cli) (built: Sep 29 2022 19:26:44) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.11, Copyright (c), by Zend Technologies
    with Xdebug v3.1.5, Copyright (c) 2002-2022, by Derick Rethans
```

Composer
```/var/www/html # composer --version
Composer version 2.4.2 2022-09-14 16:11:15
```

Simplified
```
/var/www/html # composer require google/apiclient
Using version ^2.12 for google/apiclient
./composer.json has been updated
Running composer update google/apiclient
Loading composer repositories with package information
Updating dependencies
Lock file operations: 6 installs, 0 updates, 0 removals
  - Locking firebase/php-jwt (v6.3.1)
  - Locking google/apiclient (v2.12.6)
  - Locking google/apiclient-services (v0.274.0)
  - Locking google/auth (v1.23.1)
  - Locking paragonie/constant_time_encoding (v2.6.3)
  - Locking phpseclib/phpseclib (3.0.17)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 6 installs, 0 updates, 0 removals
  - Downloading google/apiclient-services (v0.274.0)
  - Installing paragonie/constant_time_encoding (v2.6.3): Extracting archive
  - Installing phpseclib/phpseclib (3.0.17): Extracting archive
  - Installing firebase/php-jwt (v6.3.1): Extracting archive
  - Installing google/auth (v1.23.1): Extracting archive
  - Installing google/apiclient-services (v0.274.0): Extracting archive
  - Installing google/apiclient (v2.12.6): Extracting archive
 5/6 [=======================>----]  83%
    Install of google/apiclient-services failed
The following exception is caused by a process timeout
Check https://getcomposer.org/doc/06-config.md#process-timeout for details

In Process.php line 1204:

  The process "'/usr/bin/unzip' -qq '/var/www/html/vendor/composer/tmp-ac97ba793f26546f414fddb65379ccf8' -d '/var/www/html/vendor/composer/76037618'" exceeded the timeout of 300 seconds.


require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]
```

Then I ran `composer require google/apiclient-services -vvv` and the got stuck while downloading

//codeload.github.com/googleapis/google-api-php-client-services/legacy.zip/670c3854fffc2f642efa86b083e2664fd55435e1

When researching the last hash I stepped into which tells me it looks like an ISP issue, maybe a VPN connection helps you

**Comment by bshaffer** [comment]
This seems like the composer `pre-autoload-dump` task is trying to cleanup a bunch of the services, but does not have permission. Are you doing a limited install as described [here](https://github.com/googleapis/google-api-php-client#cleaning-up-unused-services)? If so, I would try to make sure the filesystem provides the proper file permissions to the user who is executing the `composer install` command.

**Comment by BobDankert** [comment]
I am not doing a limited install. I do not have `pre-autoload-dump` defined in my composer.json file. Also, I'm getting the error described above while running the install command as root on my docker instance, so I find it hard to believe it would be a permissions issue?

**Comment by sherry-channel-capital** [comment]
Also getting the same.

**Comment by wildMonkey** [comment]
I had this problem last week too and it got solved on its own on the second try. 
But for my colleague, it keeps failing:

```
- Installing google/apiclient-services failed

Could not delete /var/www/html/vendor/composer/d0d5f5a2/googleapis-google-api-php-clien
 t-services-ce77477/src/Sheets:
 ```
 
 Version 12.3

**Comment by marcelobcortes** [comment]
Solved by including the [release](https://github.com/googleapis/google-api-php-client#download-the-release). Big annoyance.

**Comment by deCastongrene** [comment]
In my case, this was caused by composer process timeout. Giving it more time to complete fixed it:

COMPOSER_PROCESS_TIMEOUT=600 composer install

More info: https://koop.sh/software/fix-composer-process-timeout-issues/

**Comment by odepiesse** [comment]
> In my case, this was caused by composer process timeout. Giving it more time to complete fixed it:
> 
> COMPOSER_PROCESS_TIMEOUT=600 composer install
> 
> More info: https://koop.sh/software/fix-composer-process-timeout-issues/

It worked !

**Comment by jazbek** [comment]
> In my case, this was caused by composer process timeout. Giving it more time to complete fixed it:
> 
> COMPOSER_PROCESS_TIMEOUT=600 composer install
> 
> More info: https://koop.sh/software/fix-composer-process-timeout-issues/

That link is 404, new link: https://koop.sh/software/fix-composer-process-timeout-issues-2020072187/

I tried this option from the article:

```
scripts: {
  "pre-install-cmd": [
    "Composer\Config::disableProcessTimeout"
  ]
}
```
and that did not fix it for me. I may try setting the timeout via the config file, but our install script takes around 20 minutes to run each time, so it's taking me a long time to troubleshoot. Will post back if I have any updates, but wanted to share the updated link, at least.

**Comment by Carmageddon** [comment]
Just a note, what worked for me, adding timeout set to 1200 in config (due to old laptop, and large size of package being extracted:
```
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true,
        "process-timeout": 1200
    }
```

This is a Composer bug; the outcome of a function should not depend on how old (or fast) the hardware running it is.
It should work the same for all team member regardless of the age of their hardware.. eventually :)

**Comment by amrikarisma** [comment]
> Just a note, what worked for me, adding timeout set to 1200 in config (due to old laptop, and large size of package being extracted:
> 
> ```
>     "config": {
>         "preferred-install": "dist",
>         "sort-packages": true,
>         "optimize-autoloader": true,
>         "process-timeout": 1200
>     }
> ```
> 
> This is a Composer bug; the outcome of a function should not depend on how old (or fast) the hardware running it is. It should work the same for all team member regardless of the age of their hardware.. eventually :)

It's work. Thanks!

**Comment by saranshdhingra** [comment]
Thanks a lot for the fix folks.
I have [added this info in the readme](https://github.com/googleapis/google-api-php-client/pull/2504) and should be helpful for anyone going through this from now on.

**Comment by theoreticalsampling** [comment]
The only solution that worked for me was using composer install --prefer-source

I am also in docker, on wsl2 and windows

**Comment by twfahey1** [comment]
My issue wasn't time related, it would happen predictably and well before any sort of timeout... The reason I arrived at this thread was searching up a similar composer file system error around an issue deleting a file during a `composer install`... the bottom line in my case was file system permissions - essentially `chown`ing all the dirs composer had to touch made the operation successful, which makes sense in retrospect. I think this comes down to how composer handles a situation where a location it's trying to do the file operation on isn't accessible. Hope this might help some future explorers as I go to close this tab out. Cheers!

**Comment by dgpro** [comment]
I had to delete `vendor/composer` on host machine and then docker was update to run `compose update`

**Comment by ethnetsky** [comment]
I had the same problem, where I detected that it was due to timeout...
"exceeded the timeout of 300 seconds."

Then use this command:
$ composer config --global process-timeout 2000

Where I set the timeout to 2000, then ran the command again: checking "--preferer-source" and also "--ignore-platform-reqs"
$ composer require google/apiclient:^2.18.0 --prefer-source --ignore-platform-reqs
 
This helped me for WSL2.
